### ISSUE TITLE
Empty seeder, makes it annoying to contribute

### ISSUE THREAD

**Issue by reneweteling** [hackersandfounders/building#1]
Hey guys,

There is an issue with the checking out times, so i wanted to create a PR, only after pulling, there is no data... this makes creating a quick fix a bit annoying, and the treshold to big to actually contribute.

Could you fix the seeder, so we can develop something with actual data?

:+1:

**Comment by joris** [comment]
Is it for the Rails backend? That only offers an API that the checkinboard frontend (Angular app) connects with. Or did you mean the backend?

Joris
+31-6-27032803

Typos courtesy of my iPhone

**Comment by joris** [comment]
Good point! Will fix later next few days

**Comment by reneweteling** [comment]
:+1: :bow:
